import { Deal } from "@/data/deals";
import { Document, mockDocuments } from "@/data/documents";
import { Invitation } from "@/data/invitations";
import { format, parseISO } from "date-fns";

interface MemoConfig {
  deal: Deal;
  invitation: Invitation;
  accessTier: "early" | "full" | "legal";
  ndaSigned: boolean;
  lenderName?: string;
}

interface FinancialProjection {
  year: number;
  revenue: number;
  ebitda: number;
  leverage: number;
  interestCoverage: number;
}

// Risk categories for placeholder content
const RISK_CATEGORIES = {
  market: ["Market competition may intensify", "Economic downturn sensitivity", "Regulatory environment changes"],
  operational: ["Key person dependency", "Technology obsolescence risk", "Supply chain concentration"],
  financial: ["Leverage-related refinancing risk", "Interest rate sensitivity", "Working capital volatility"],
  industry: ["Sector cyclicality", "Customer concentration", "Pricing pressure from large customers"],
};

/**
 * Generates a Credit Memo document for a lender
 * Respects access tier and NDA status
 */
export function generateCreditMemo(config: MemoConfig): string {
  const { deal, invitation, accessTier, ndaSigned, lenderName } = config;

  if (!ndaSigned) {
    return generateRestrictedMemo(deal);
  }

  const documents = getAccessibleDocuments(deal.id, accessTier);
  const financials = generateFinancialProjections(deal);
  const risks = selectRelevantRisks(deal.sector);

  const sections: string[] = [];

  // Header
  sections.push(generateHeader(deal, lenderName));

  // Disclaimer
  sections.push(generateDisclaimer());

  // Executive Summary
  sections.push(generateExecutiveSummary(deal));

  // Deal Terms
  sections.push(generateDealTerms(deal));

  // Credit Highlights
  sections.push(generateCreditHighlights(deal, accessTier));

  // Financial Projections (if access tier allows)
  if (accessTier === "full" || accessTier === "legal") {
    sections.push(generateFinancialSection(deal, financials));
  }

  // Key Risks
  sections.push(generateRisksSection(risks));

  // Timeline
  sections.push(generateTimelineSection(deal));

  // Data Room Index
  sections.push(generateDataRoomIndex(documents, accessTier));

  // Footer
  sections.push(generateFooter());

  return sections.join("\n\n");
}

function generateRestrictedMemo(deal: Deal): string {
  return `# Credit Memo - RESTRICTED ACCESS

## ${deal.dealName}

---

**Access Restricted**

This credit memo is only available after signing the required NDA.

Please sign the Confidentiality Agreement to access full deal information.

---

*This document is generated by CapitalFlow.*
*Date: ${format(new Date(), "MMMM d, yyyy")}*
`;
}

function generateHeader(deal: Deal, lenderName?: string): string {
  const date = format(new Date(), "MMMM d, yyyy");

  return `# Lender Credit Memo

## ${deal.dealName}

**Borrower:** ${deal.borrowerName}
**Sponsor:** ${deal.sponsor}
**Industry:** ${deal.sector}

${lenderName ? `**Prepared for:** ${lenderName}` : ""}
**Date Generated:** ${date}

---`;
}

function generateDisclaimer(): string {
  return `> **DISCLAIMER**
>
> Draft summary for internal use only. Please refer to source documents in the Data Room for complete and binding terms. This memo is provided as a convenience and does not constitute investment advice or a commitment to lend. All information is subject to change and should be verified against official documentation.`;
}

function generateExecutiveSummary(deal: Deal): string {
  const facilitySize = formatCurrency(deal.facilitySize);

  return `## Executive Summary

${deal.sponsor} is sponsoring the financing of **${deal.borrowerName}** ("the Company"), a leading player in the **${deal.sector}** sector.

### Transaction Overview

| Attribute | Details |
|-----------|---------|
| **Borrower** | ${deal.borrowerName} |
| **Sponsor** | ${deal.sponsor} |
| **Industry** | ${deal.sector} |
| **Facility Type** | ${deal.instrument} - ${deal.facilityType} |
| **Facility Size** | ${facilitySize} |
| **Currency** | ${deal.currency} |
| **Current Stage** | ${deal.stage} |

The Company demonstrates strong market positioning with recurring revenue characteristics typical of ${deal.sector} businesses.`;
}

function generateDealTerms(deal: Deal): string {
  const { pricing } = deal;
  const spreadRange = pricing.spreadLowBps === pricing.spreadHighBps
    ? `${pricing.spreadLowBps} bps`
    : `${pricing.spreadLowBps} - ${pricing.spreadHighBps} bps`;

  const allInYieldLow = (pricing.spreadLowBps / 100) + 5.25; // Assuming ~5.25% base rate
  const allInYieldHigh = (pricing.spreadHighBps / 100) + 5.25;
  const yieldRange = allInYieldLow === allInYieldHigh
    ? `${allInYieldLow.toFixed(2)}%`
    : `${allInYieldLow.toFixed(2)}% - ${allInYieldHigh.toFixed(2)}%`;

  return `## Deal Terms

### Pricing Structure

| Term | Value |
|------|-------|
| **Benchmark** | ${pricing.benchmark} |
| **Spread** | ${spreadRange} |
| **OID** | ${pricing.oid}% |
| **Fees** | ${pricing.feesPct}% |
| **Est. All-In Yield** | ${yieldRange} |

### Facility Details

| Attribute | Details |
|-----------|---------|
| **Facility Type** | ${deal.facilityType} |
| **Instrument** | ${deal.instrument} |
| **Target Size** | ${formatCurrency(deal.targetSize)} |
| **Current Committed** | ${formatCurrency(deal.committed)} (${(deal.committedPct).toFixed(0)}%) |`;
}

function generateCreditHighlights(deal: Deal, accessTier: string): string {
  // Generate sector-specific highlights
  const highlights = getSectorHighlights(deal.sector);

  let content = `## Credit Highlights

### Investment Thesis

`;

  highlights.forEach((highlight, index) => {
    content += `${index + 1}. **${highlight.title}** - ${highlight.description}\n`;
  });

  if (accessTier !== "early") {
    content += `
### Covenant Structure

`;
    if (deal.covenants && deal.covenants.length > 0) {
      content += `| Covenant | Type | Threshold | Pro Forma |
|----------|------|-----------|-----------|
`;
      deal.covenants.forEach(cov => {
        const thresholdStr = cov.unit === "$"
          ? formatCurrency(cov.threshold)
          : `${cov.threshold}${cov.unit}`;
        const proFormaStr = cov.unit === "$"
          ? formatCurrency(cov.proForma)
          : `${cov.proForma}${cov.unit}`;
        content += `| ${cov.name} | ${cov.type} | ${thresholdStr} | ${proFormaStr} |\n`;
      });
    } else {
      content += `Covenant terms to be confirmed. Please refer to the Credit Agreement in the Data Room.`;
    }
  }

  return content;
}

function generateFinancialSection(deal: Deal, projections: FinancialProjection[]): string {
  let content = `## Financial Highlights

### Projected Performance

| Year | Revenue | EBITDA | Leverage | Interest Coverage |
|------|---------|--------|----------|-------------------|
`;

  projections.forEach(proj => {
    content += `| Year ${proj.year} | ${formatCurrency(proj.revenue)} | ${formatCurrency(proj.ebitda)} | ${proj.leverage.toFixed(2)}x | ${proj.interestCoverage.toFixed(2)}x |\n`;
  });

  content += `
*Financial projections are based on management estimates and model assumptions. Actual results may vary.*`;

  return content;
}

function generateRisksSection(risks: string[]): string {
  let content = `## Key Risks

The following risk factors should be considered when evaluating this investment:

`;

  risks.forEach((risk, index) => {
    content += `${index + 1}. ${risk}\n`;
  });

  content += `
*This is not an exhaustive list. Please review the full Risk Factors section in the Lender Presentation.*`;

  return content;
}

function generateTimelineSection(deal: Deal): string {
  const timeline = [
    { label: "Launch Date", date: deal.launchDate },
    { label: "IOI Deadline", date: deal.ioiDate },
    { label: "Commitment Deadline", date: deal.commitmentDate },
    { label: "Target Close", date: deal.closeDate },
    { label: "Hard Close", date: deal.hardCloseDate },
  ].filter(t => t.date);

  let content = `## Transaction Timeline

| Milestone | Date |
|-----------|------|
`;

  timeline.forEach(t => {
    const formattedDate = t.date ? format(parseISO(t.date), "MMMM d, yyyy") : "TBD";
    content += `| ${t.label} | ${formattedDate} |\n`;
  });

  return content;
}

function generateDataRoomIndex(documents: Document[], accessTier: string): string {
  let content = `## Data Room Index

The following documents are available in the Data Room based on your access tier (**${accessTier.toUpperCase()}**):

`;

  // Group by category
  const grouped = documents.reduce((acc, doc) => {
    if (!acc[doc.category]) {
      acc[doc.category] = [];
    }
    acc[doc.category].push(doc);
    return acc;
  }, {} as Record<string, Document[]>);

  Object.entries(grouped).forEach(([category, docs]) => {
    content += `### ${category}\n\n`;
    docs.forEach(doc => {
      const badge = doc.isNew ? " **(NEW)**" : doc.isUpdated ? " **(UPDATED)**" : "";
      content += `- ${doc.name} (${doc.version})${badge}\n`;
    });
    content += "\n";
  });

  if (documents.length === 0) {
    content += `*No documents currently available at your access tier.*`;
  }

  return content;
}

function generateFooter(): string {
  return `---

## Contact Information

For questions regarding this transaction, please contact your deal team representative through the CapitalFlow messaging system.

---

*Generated by CapitalFlow | ${format(new Date(), "MMMM d, yyyy 'at' h:mm a")}*

*Confidential - For recipient use only*`;
}

// Helper Functions

function formatCurrency(value: number): string {
  if (value >= 1_000_000_000) {
    return `$${(value / 1_000_000_000).toFixed(2)}B`;
  }
  if (value >= 1_000_000) {
    return `$${(value / 1_000_000).toFixed(1)}M`;
  }
  if (value >= 1_000) {
    return `$${(value / 1_000).toFixed(0)}K`;
  }
  return `$${value.toFixed(0)}`;
}

function getAccessibleDocuments(dealId: string, accessTier: string): Document[] {
  const tierOrder = { early: 1, full: 2, legal: 3 };
  const userTierLevel = tierOrder[accessTier as keyof typeof tierOrder] || 1;

  return mockDocuments.filter(doc => {
    if (doc.dealId !== dealId) return false;
    const docTierLevel = tierOrder[doc.accessTier as keyof typeof tierOrder] || 1;
    return docTierLevel <= userTierLevel;
  });
}

function generateFinancialProjections(deal: Deal): FinancialProjection[] {
  // Generate placeholder projections based on deal size
  const baseRevenue = deal.facilitySize * 2; // Rough assumption
  const baseEbitda = baseRevenue * 0.25; // 25% margin assumption
  const baseLeverage = 4.0;

  return [
    {
      year: 1,
      revenue: baseRevenue,
      ebitda: baseEbitda,
      leverage: baseLeverage,
      interestCoverage: 2.5,
    },
    {
      year: 3,
      revenue: baseRevenue * 1.25,
      ebitda: baseEbitda * 1.3,
      leverage: baseLeverage * 0.85,
      interestCoverage: 3.0,
    },
    {
      year: 5,
      revenue: baseRevenue * 1.5,
      ebitda: baseEbitda * 1.6,
      leverage: baseLeverage * 0.7,
      interestCoverage: 3.5,
    },
  ];
}

function selectRelevantRisks(sector: string): string[] {
  const risks: string[] = [];

  // Add 1-2 from each category
  risks.push(RISK_CATEGORIES.market[Math.floor(Math.random() * RISK_CATEGORIES.market.length)]);
  risks.push(RISK_CATEGORIES.operational[Math.floor(Math.random() * RISK_CATEGORIES.operational.length)]);
  risks.push(RISK_CATEGORIES.financial[Math.floor(Math.random() * RISK_CATEGORIES.financial.length)]);
  risks.push(RISK_CATEGORIES.industry[Math.floor(Math.random() * RISK_CATEGORIES.industry.length)]);

  // Add sector-specific risk
  const sectorRisks: Record<string, string> = {
    "Enterprise SaaS": "Software market saturation and commoditization",
    "Healthcare": "Healthcare reimbursement and regulatory changes",
    "Infrastructure": "Long-term capex requirements and maintenance costs",
    "Consumer": "Consumer spending sensitivity to economic cycles",
    "TMT": "Rapid technology change and disruption risk",
    "Financial Services": "Regulatory capital requirements and compliance costs",
  };

  if (sectorRisks[sector]) {
    risks.push(sectorRisks[sector]);
  }

  return risks;
}

function getSectorHighlights(sector: string): { title: string; description: string }[] {
  const highlights: Record<string, { title: string; description: string }[]> = {
    "Enterprise SaaS": [
      { title: "Recurring Revenue Model", description: "High percentage of ARR with strong net retention rates" },
      { title: "Scalable Platform", description: "Cloud-native infrastructure enabling efficient growth" },
      { title: "Mission-Critical Product", description: "Deep customer integration and high switching costs" },
    ],
    "Healthcare": [
      { title: "Defensive Sector", description: "Healthcare demand remains stable across economic cycles" },
      { title: "Aging Demographics", description: "Growing addressable market driven by demographic trends" },
      { title: "Regulatory Moat", description: "Compliance requirements create barriers to entry" },
    ],
    "Infrastructure": [
      { title: "Essential Services", description: "Critical infrastructure with inelastic demand" },
      { title: "Long-Term Contracts", description: "Contracted cash flows provide revenue visibility" },
      { title: "Inflation Protection", description: "Many contracts include inflation escalators" },
    ],
    default: [
      { title: "Market Position", description: "Strong competitive positioning in target market segments" },
      { title: "Cash Flow Generation", description: "Consistent EBITDA margins supporting debt service" },
      { title: "Growth Opportunity", description: "Identified expansion initiatives with favorable risk/return" },
    ],
  };

  return highlights[sector] || highlights.default;
}

/**
 * Downloads the credit memo as a file
 */
export function downloadCreditMemo(content: string, dealName: string, format: "md" | "txt" = "md"): void {
  const sanitizedName = dealName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const dateStr = format === "md"
    ? new Date().toISOString().split("T")[0]
    : new Date().toISOString().split("T")[0];
  const filename = `credit-memo-${sanitizedName}-${dateStr}.${format}`;

  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
